name: build-docker-image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '7 0 * * sun'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout docker-software-base
      uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensciencegrid/software-base
        tags: fresh,${{ steps.mkdatetag.outputs.dtag }}

    - name: dispatch build frontier-squid
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: opensciencegrid/docker-frontier-squid
        event-type: dispatch-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

