name: build-docker-image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout docker-software-base
      uses: actions/checkout@v2

    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: test test Build and push Docker images
      run: echo test test ${{ steps.mkdatetag.outputs.dtag }}

    - name: dispatch build frontier-squid
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: edquist/docker-frontier-squid
        event-type: dispatch-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

